[tool.poetry]
name = "mathanimation"
version = "0.1.0"
description = ""
authors = ["kaytaka0 <sora3takashima@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
